import React from "react"; 
import profPic from "../Images/profilePic.jpeg"; 

export default function Bio() {
    return (
        <div className="bio--color">
            <img className="bio--profPic" src={profPic} alt=""></img>
            <div className="bio--aMe">
                <h2>About Me</h2>
                <p className="bio--aMePara">Things about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me toThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgeThings about me tomato sauce was in the fridgemato sauce was in the fridge</p>
            </div>
            <h2 className="bio--proj">Projects</h2>
            
        </div>
    )
}